algo = input('digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(algo)))
print('O valor é numérico: {} '.format(algo.isnumeric()))
print('O valor é alfanumérico: {} '.format(algo.isalnum()))
print('O valor é alfabético: {} '.format(algo.isalpha()))
print('O valor só tem espaços: {} '.format(algo.isspace()))
print('O valor está em maiusculas: {} '.format(algo.isupper()))
print('O valor está em minusculas: {} '.format(algo.islower()))
print('O valor está capitalizado: {} '.format(algo.istitle()))